### ISSUE TITLE
ModuleNotFoundError: No module named 'fft_delta'

### ISSUE THREAD

**Issue by mohammed-dawoud** [teuron/optimal_truncated_noise#1]
Dear Sir @teuron ,  
I have the following issue while I am trying to run the code. the code requires some dependencies such as PyTorch, numpy, Scipy,..
I installed them but I still have "ModuleNotFoundError: No module named 'fft_delta'" issue I could not resolve.
I use Ubuntu platform
I do not want compositions in current state I just want to generate optimal truncated noise simply. So If you have some recommendations or simple steps that might help me it will be fine.
Thanks in advance
M. Dawoud

**Comment by teuron** [comment]
Added missing file. Thanks for the hint!

**Comment by mohammed-dawoud** [comment]
Thank you very much for your help
